"""create publications table

Revision ID: 98a614632c88
Revises: c6ca1fb3c509
Create Date: 2026-06-22 20:32:53.744043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a614632c88'
down_revision: Union[str, Sequence[str], None] = 'c6ca1fb3c509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('modality', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modality IS NULL OR modality IN ('remote', 'onsite', 'hybrid')", name='ck_publications_modality'),
    sa.CheckConstraint("type IN ('general', 'internship', 'job', 'social_service', 'freelance', 'announcement')", name='ck_publications_type'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_author_id'), 'publications', ['author_id'], unique=False)
    op.create_index(op.f('ix_publications_is_active'), 'publications', ['is_active'], unique=False)
    op.create_index(op.f('ix_publications_type'), 'publications', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_type'), table_name='publications')
    op.drop_index(op.f('ix_publications_is_active'), table_name='publications')
    op.drop_index(op.f('ix_publications_author_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
